### PR TITLE
Add simple GLib.check_version example

### PR DESCRIPTION
**Pull request by cedlemo**
@mvz ,

I will start with very simple examples that focus on GLib and Gio for the gir_ffi repository. 

Is there any copyright lines that I should add in the examples.

Have you some conventions that I must follow when I write the examples like:

*    always use double-quotes for the strings or use single-quote for the strings that don't need interpolation

...

### CODE REVIEW

**Comment by mvz** [comment]
@cedlemo regarding code conventions, I use RuboCop to enforce them. If `bundle exec rake rubocop` passes, things should be alright in that respect.

**Comment by cedlemo** [comment]
After launching the command, it seems that 2 cops are not recognized and that 2 offences are detected (not in my file).

```
rake rubocop
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.x-compliant syntax, but you are running 2.3.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Running RuboCop...
Warning: unrecognized cop Style/FrozenStringLiteralComment found in /home/cedlemo/Projets/Ruby/gir_ffi/.rubocop.yml
Inspecting 278 files
..........................................................................................................................................................................Warning: unrecognized cop Style/FrozenStringLiteralComment found in /home/cedlemo/Projets/Ruby/gir_ffi/.rubocop.yml
Warning: unrecognized cop Style/FrozenStringLiteralComment found in /home/cedlemo/Projets/Ruby/gir_ffi/test/.rubocop.yml
........................C...................................................................................

Offenses:

test/integration/generated_utility_test.rb:73:32: C: Style/SpaceInsideBlockBraces: Space inside empty braces detected.
      instance.watch_dir('/') { }
                               ^
test/integration/generated_utility_test.rb:146:1: C: Style/TrailingBlankLines: 1 trailing blank lines detected.

278 files inspected, 2 offenses detected
RuboCop failed!
```

**Comment by mvz** [comment]
Right. Current master is a bit off. Better try `bundle exec rubocop examples` and ignore the warning about unrecognized cop names.

**Comment by mvz** [comment]
Regarding the subject matter of examples: I think I am looking mostly for examples that are full small programs rather than just a demonstration of one particular function. As such, the `mainloop.rb` has shrunken so much over time that it is no longer a useful example. The newer `clutter.rb` example is more in line with what I'm thinking of.

**Comment by cedlemo** [comment]
> Regarding the subject matter of examples: I think I am looking mostly for examples that are full small programs rather than just a demonstration of one particular function.

Ok I will close this pull request. And try to find some ideas.

**Pull request closed without merging**
