### PR TITLE
try to unset gvalue on finalize

### PR DESCRIPTION
**Pull request by jcupitt**
see https://github.com/mvz/gir_ffi/issues/52

### CODE REVIEW

**Comment by jcupitt** [comment]
I was only guessing how to do this, I'm sure I've done a very bad job. But it seems to fix this memleak for me.

**Comment by jcupitt** [comment]
The Travis build is failing and I'm not really sure why. A problem with bundling? I think the patch works, more or less.

**Comment by mvz** [comment]
I'll take a look.

**Comment by mvz** [comment]
Travis fails to build current master now, with very odd errors.

**Comment by mvz** [comment]
I've updated dependencies to fix the build failures in master and rebased your commits on top of it.

**Comment by mvz** [comment]
Merged in d8d253055b27758457d8ae9b1a0ac472e23093b2

**Comment by mvz** [comment]
Thanks, @jcupitt!

**Comment by jcupitt** [comment]
Thank you very much for fixing this, @mvz! 

There's (as far as I know) only one leak left now in the ruby bindings for my library. I've spent some time looking at #53 but I can't see where to add the finalizer there, unfortunately.

**Pull request closed without merging**
